# Site settings
title: clock
email: zhongchiyu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Programmer, for now.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cattail.me" # the base hostname & protocol for your site
twitter_username: zhongchiyu
github_username: cattail

    # Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
