# Site settings
title: clock
email: zhongchiyu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Programmer, for now.
    Open Source Fucker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cattail.me" # the base hostname & protocol for your site
twitter_username: zhongchiyu
github_username: cattail

defaults:
  -
    scope:
      path: _posts/default
    values:
      layout: default
      lang: en
      permalink: /:categories/:year/:month/:day/:title.html
  -
    scope:
      path: _posts/zh
    values:
      layout: default
      lang: zh
      permalink: /:categories/:year/:month/:day/:title.html

    # Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
